# Copyright 2022 The IREE Authors
#
# Licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception

name: Benchmark Report

on:
  workflow_run:
    workflows: ["Test"]
    types: [completed]

concurrency:
  # A PR number if a pull request and otherwise the commit hash. This cancels
  # queued and in-progress runs for the same PR (presubmit) or commit
  # (postsubmit).
  group: ${{ github.event.number || github.sha }}-report
  cancel-in-progress: true

jobs:
  process_benchmark_results:
    runs-on: ubuntu-20.04
    if: github.event.workflow_run.conclusion == 'success'
    env:
      CI_GCS_DIR: gs://iree-github-actions-${{ github.event.workflow_run.event == 'pull_request' && 'presubmit' || 'postsubmit' }}-artifacts/${{ github.event.workflow_run.id }}/${{ github.event.workflow_run.run_attempt }}
      BENCHMARK_RESULTS_METADATA: benchmark-results-metadata.json
    steps:
      - name: "Dummy"
        run: |
          echo "${CI_GCS_DIR}"
          gcloud alpha storage cp "${CI_GCS_DIR}/${BENCHMARK_RESULTS_METADATA}" "${BENCHMARK_RESULTS_METADATA}"
          echo "${{ toJSON(github.event.workflow_run) }}"
