# Copyright 2022 The IREE Authors
#
# Licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception

name: Benchmark Report

on:
  workflow_run:
    workflows: ["Test"]
    types: [completed]

concurrency:
  # A PR number if a pull request and otherwise the commit hash. This cancels
  # queued and in-progress runs for the same PR (presubmit) or commit
  # (postsubmit).
  group: ${{ github.event.workflow_run.pull_requests[0].number || github.sha }}-benchmark-report
  cancel-in-progress: true

env:
  CI_STAGE: ${{ github.event.workflow_run.event == 'pull_request' && 'presubmit' || 'postsubmit' }}
  CI_RUN_ID: ${{ github.event.workflow_run.id }}
  CI_RUN_ATTEMPT: ${{ github.event.workflow_run.run_attempt }}

jobs:
  check_benchmark_job:
    if: true
    runs-on: ubuntu-20.04
    outputs:
      job-conclusion: ${{ steps.check.outputs.job-conclusion }}
    steps:
      - name: "Checking benchmark job"
        id: check
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh api \
            -H "Accept: application/vnd.github+json" \
            --jq '.jobs | map(select(.name=="setup"))[0] | .conclusion' \
            "/repos/${GITHUB_REPOSITORY}/actions/runs/${CI_RUN_ID}/attempts/${CI_RUN_ATTEMPT}/jobs" \
            > conclusion
          echo "job-conclusion=$(cat conclusion)" >> "${GITHUB_OUTPUT}"

  report_benchmark_results:
    needs: check_benchmark_job
    # TODO(#11076): Temporarily disabled until we migrate the database.
    if: true && needs.check_benchmark_job.outputs.job-conclusion == 'success'
    runs-on: ubuntu-20.04
    environment: postsubmit
    steps:
      - name: "Checking out repository"
        uses: actions/checkout@7884fcad6b5d53d10323aee724dc68d8b9096a2e # v2
      - name: "Downloading artifacts"
        id: download
        env:
          CI_GCS_DIR: gs://iree-github-actions-${{ env.CI_STAGE }}-artifacts/${{ env.CI_RUN_ID }}/${{ env.CI_RUN_ATTEMPT }}
          BENCHMARK_COMMENT_JSON: benchmark-comment.json
        run: |
          # gcloud alpha storage cp \
          #   "${CI_GCS_DIR}/${BENCHMARK_COMMENT_ARTIFACT}" \
          #   "${BENCHMARK_COMMENT_ARTIFACT}" || export DOWNLOAD_STATUS="failed"
          curl \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}"\
            -H "X-GitHub-Api-Version: 2022-11-28" \
            "https://api.github.com/repos/pzread/iree/actions/runs/${CI_RUN_ID}/artifacts" | \
            jq --raw-output '.artifacts[0].archive_download_url' > url.txt
          curl \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}"\
            -H "X-GitHub-Api-Version: 2022-11-28" \
            -L \
            -o artifact.zip \
            "$(cat url.txt)"
          unzip -p artifact.zip > "${BENCHMARK_COMMENT_JSON}"
          echo "benchmark-comment-json=${BENCHMARK_COMMENT_JSON}" >> "${GITHUB_OUTPUT}"
      - name: Posting comments
        if: env.CI_STAGE == 'presubmit'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GIST_BOT_TOKEN: ${{ secrets.GIST_BOT_TOKEN }}
          # Get PR number from the event instead of the untrusted comment
          # artifact, to make sure we won't incorrectly update other PRs.
          PR_NUMBER: ${{ github.event.workflow_run.pull_requests[0].number }}
          IREE_DASHBOARD_URL: https://perf.iree.dev
          BENCHMARK_COMMENT_JSON: ${{ steps.download.outputs.benchmark-comment-json }}
        run: |
          ./build_tools/benchmarks/post_benchmark_comment.py \
            --verbose \
            --pr_number "${PR_NUMBER}" \
            "${BENCHMARK_COMMENT_JSON}"
