# Copyright 2022 The IREE Authors
#
# Licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception

name: Test

on:
  workflow_dispatch:
  pull_request:

concurrency:
  # Version 2
  # A PR number if a pull request and otherwise the commit hash. This cancels
  # queued and in-progress runs for the same PR (presubmit) or commit
  # (postsubmit).
  group: ${{ github.event.number || github.sha }}-test
  cancel-in-progress: true

env:
  # This needs to be in env instead of the outputs of setup because it contains
  # the run attempt and we want that to be the current attempt, not whatever
  # attempt the setup step last ran in.
  GCS_DIR: gs://iree-github-actions-${{ github.event_name == 'pull_request' && 'presubmit' || 'postsubmit' }}-artifacts/${{ github.run_id }}/${{ github.run_attempt }}

jobs:
  setup:
    runs-on: ubuntu-20.04
    steps:
      - name: "Checking out repository"
        uses: actions/checkout@7884fcad6b5d53d10323aee724dc68d8b9096a2e # v2
      - name: "Install"
        run: |
          pip install markdown_strings
      - name: "Dummy"
        env:
          IREE_DASHBOARD_URL: www.example.com
          IREE_BUILD_URL: https://github.com/iree-org/iree/actions/runs/${{ github.run_id }}/attempts/${{ github.run_attempt }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
        run: |
          ./build_tools/benchmarks/generate_benchmark_comment.py \
            --pr_commit "${GITHUB_SHA}" \
            --pr_number "${PR_NUMBER}" \
            --build_url="${IREE_BUILD_URL}" \
            --benchmark_files ./c2-standard-16-benchmark-results.json \
            --output benchmark_comment.json
          echo "${GCS_DIR}"
